# Generated by Django 3.1.7 on 2021-05-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='emergencyContact',
            field=models.CharField(max_length=13, null=True, verbose_name='Emergency Contact'),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='profilePicture',
            field=models.ImageField(null=True, upload_to='', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='signature',
            field=models.ImageField(null=True, upload_to='', verbose_name='Signature'),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='uniqueID',
            field=models.CharField(default='C9DA4', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='Unique ID'),
        ),
    ]
