# Generated by Django 3.1.7 on 2021-05-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0004_auto_20210510_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='uniqueID',
            field=models.CharField(default='6EE3A', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='Unique ID'),
        ),
    ]
