# Generated by Django 3.1.7 on 2021-05-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0006_auto_20210513_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainee',
            name='purpose',
        ),
        migrations.AddField(
            model_name='trainee',
            name='bloodGroup',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=255, null=True, verbose_name='Blood Group'),
        ),
        migrations.AddField(
            model_name='trainee',
            name='documentImage',
            field=models.ImageField(null=True, upload_to='', verbose_name='Document Image'),
        ),
        migrations.AddField(
            model_name='trainee',
            name='status',
            field=models.BooleanField(default=False, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='uniqueID',
            field=models.CharField(default='92CCD', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='Unique ID'),
        ),
    ]
