# Generated by Django 3.1.7 on 2021-05-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0007_auto_20210514_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('desc', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='trainee',
            name='uniqueID',
            field=models.CharField(default='ACA58', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='Unique ID'),
        ),
        migrations.AddField(
            model_name='trainee',
            name='courses',
            field=models.ManyToManyField(to='trainee.Course'),
        ),
    ]
