# Generated by Django 3.1.7 on 2021-05-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0016_auto_20210519_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainee',
            old_name='courses',
            new_name='course',
        ),
        migrations.AlterField(
            model_name='trainee',
            name='uniqueID',
            field=models.CharField(default='B332D', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='Unique ID'),
        ),
    ]
