# Generated by Django 3.1.7 on 2021-05-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0017_auto_20210519_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='validUpto',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='uniqueID',
            field=models.CharField(default='2385E', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='Unique ID'),
        ),
    ]
