# Generated by Django 3.1.7 on 2021-05-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0019_auto_20210520_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='uniqueID',
            field=models.CharField(default='14B85', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='Unique ID'),
        ),
    ]
