# Generated by Django 3.1.7 on 2021-05-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0021_auto_20210520_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='currentCourse',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='uniqueID',
            field=models.CharField(default='0882D', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='Unique ID'),
        ),
    ]
