# Generated by Django 3.1.7 on 2021-05-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0023_auto_20210520_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='uniqueID',
            field=models.CharField(default='CB2A1', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='Unique ID'),
        ),
    ]
