# Generated by Django 3.1.7 on 2021-05-26 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0025_auto_20210526_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainee',
            name='enrolledCourses',
        ),
        migrations.AlterField(
            model_name='trainee',
            name='uniqueID',
            field=models.CharField(default='EB2FA', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='Unique ID'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(null=True, verbose_name='Start Date')),
                ('endDate', models.DateField(null=True, verbose_name='End Date')),
                ('course', models.ManyToManyField(to='trainee.Course')),
                ('trainee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainee.trainee')),
            ],
        ),
    ]
