# Generated by Django 3.1.7 on 2021-05-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0035_auto_20210528_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='uniqueID',
            field=models.CharField(default='B7B35', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='Unique ID'),
        ),
    ]
