# Generated by Django 3.1.7 on 2021-05-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0037_auto_20210530_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='uniqueID',
            field=models.CharField(default='1829E', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='Unique ID'),
        ),
    ]
