# Generated by Django 3.1.7 on 2021-05-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='reciept1',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='expense',
            name='reciept2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='revenue',
            name='reciept1',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='revenue',
            name='reciept2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='service',
            name='reciept1',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='service',
            name='reciept2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='associate',
            name='uniqueID',
            field=models.CharField(default='72EDF', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='uniqueID',
            field=models.CharField(default='85DF6', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='uniqueID',
            field=models.CharField(default='073CB', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='service',
            name='uniqueID',
            field=models.CharField(default='07DA4', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='Unique ID'),
        ),
    ]
