# Generated by Django 3.1.7 on 2021-05-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associate', '0002_auto_20210510_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='reciept1',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='reciept2',
        ),
        migrations.RemoveField(
            model_name='revenue',
            name='reciept1',
        ),
        migrations.RemoveField(
            model_name='revenue',
            name='reciept2',
        ),
        migrations.RemoveField(
            model_name='service',
            name='reciept1',
        ),
        migrations.RemoveField(
            model_name='service',
            name='reciept2',
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt1',
            field=models.ImageField(null=True, upload_to='', verbose_name='Receipt Photograph 1'),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Receipt Photograph 2'),
        ),
        migrations.AddField(
            model_name='revenue',
            name='receipt1',
            field=models.ImageField(null=True, upload_to='', verbose_name='Receipt Photograph 1'),
        ),
        migrations.AddField(
            model_name='revenue',
            name='receipt2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Receipt Photograph 2'),
        ),
        migrations.AddField(
            model_name='service',
            name='receipt1',
            field=models.ImageField(null=True, upload_to='', verbose_name='Receipt Photograph 1'),
        ),
        migrations.AddField(
            model_name='service',
            name='receipt2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Receipt Photograph 2'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='uniqueID',
            field=models.CharField(default='4FC6F', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='uniqueID',
            field=models.CharField(default='F7DBC', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='uniqueID',
            field=models.CharField(default='87695', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='service',
            name='uniqueID',
            field=models.CharField(default='B4DE2', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='Unique ID'),
        ),
    ]
