# Generated by Django 3.2.4 on 2021-06-22 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210612_1230'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Impact',
        ),
    ]
