# Generated by Django 3.1.7 on 2021-05-10 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('uniqueID', models.CharField(default='37EE0', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='studentID')),
                ('amount', models.IntegerField(null=True, verbose_name='Donation Amount')),
                ('purpose', models.CharField(choices=[('Donation', 'Donation'), ('Education', 'Education'), ('Differently Abled', 'Differently Abled'), ('Medical Aid', 'Medical Aid'), ('Ration Support', 'Ration Support'), ('Women Empowerment', 'Women Empowerment'), ('Skill Developement', 'Skill Developement')], max_length=255, null=True, verbose_name='Purpose')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=255, null=True, verbose_name='Donation Status')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
