# Generated by Django 3.2.4 on 2021-06-22 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeMaker',
            fields=[
                ('uniqueID', models.CharField(default='B151E', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='Unique ID')),
                ('profilePicture', models.ImageField(null=True, upload_to='', verbose_name='Profile Picture')),
                ('firstName', models.CharField(max_length=255, null=True, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=255, null=True, verbose_name='Last Name')),
                ('fatherName', models.CharField(max_length=255, null=True, verbose_name="Father's Name")),
                ('dateOfBirth', models.DateField(null=True, verbose_name='Date of Birth')),
                ('age', models.IntegerField(null=True, verbose_name='Age of Candidate')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')], max_length=255, null=True, verbose_name='Gender')),
                ('mobileNumber', models.CharField(max_length=13, null=True, verbose_name='Mobile Number')),
                ('emailID', models.EmailField(max_length=254, null=True, verbose_name='Email Address')),
                ('emergencyContact', models.CharField(max_length=13, null=True, verbose_name='Emergency Contact Number')),
                ('address', models.CharField(max_length=512, null=True, verbose_name='Address')),
                ('area', models.CharField(max_length=255, null=True, verbose_name='Area')),
                ('locality', models.CharField(max_length=255, null=True, verbose_name='Locality')),
                ('district', models.CharField(max_length=255, null=True, verbose_name='District')),
                ('state', models.CharField(max_length=255, null=True, verbose_name='State')),
                ('pincode', models.CharField(max_length=255, null=True, verbose_name='Pincode')),
                ('isMonthly', models.BooleanField(default=False, null=True, verbose_name='Is Monthly')),
                ('monthlyAmount', models.IntegerField(null=True, verbose_name='Monthly Donation Amount')),
                ('monthlyPurpose', models.CharField(choices=[('Donation', 'Donation'), ('Education', 'Education'), ('Differently Abled', 'Differently Abled'), ('Medical Aid', 'Medical Aid'), ('Ration Support', 'Ration Support'), ('Women Empowerment', 'Women Empowerment'), ('Skill Developement', 'Skill Developement')], max_length=25, null=True, verbose_name='Purpose of Donation')),
                ('goldenDate', models.IntegerField(null=True, verbose_name='Golden Date of Giving')),
                ('autoDebiting', models.BooleanField(default=False, null=True, verbose_name='Auto-Debiting')),
                ('isVolunteer', models.BooleanField(default=False, null=True, verbose_name='Is Volunteer')),
                ('documentType', models.CharField(choices=[('Aadhaar Card', 'Aadhaar Card'), ('Voter Card', 'Voter Card'), ('PAN Card', 'PAN Card'), ('Ration Card', 'Ration Card'), ('Passport', 'Passport'), ('Driving License', 'Driving License')], max_length=255, null=True, verbose_name='Document Type')),
                ('documentNumber', models.CharField(max_length=255, null=True, verbose_name='Document Number')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True, verbose_name='Interest')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True, verbose_name='Skill')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(choices=[('Nil', 'Nil'), ('5th Grade', '5th Grade'), ('6th Grade', '6th Grade'), ('7th Grade', '7th Grade'), ('8th Grade', '8th Grade'), ('9th Grade', '9th Grade'), ('10th Grade', '10th Grade'), ('11th Grade', '11th Grade'), ('12th Grade', '12th Grade'), ('Graduate', 'Graduate'), ('Post Graduate', 'Post Graduate')], max_length=25, null=True, verbose_name='Education')),
                ('specialization', models.CharField(max_length=250, null=True, verbose_name='Specialization')),
                ('duration', models.CharField(choices=[('1 Year', '1 Year'), ('5 Year', '5 Year'), ('10 Year', '10 Year'), ('Lifetime', 'Lifetime')], max_length=25, null=True, verbose_name='Duration')),
                ('hours', models.IntegerField(null=True, verbose_name='Volunteering Hours')),
                ('changemaker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='changemaker.changemaker')),
                ('interests', models.ManyToManyField(to='changemaker.Interest')),
                ('skills', models.ManyToManyField(to='changemaker.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('uniqueID', models.CharField(default='B516C', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='studentID')),
                ('amount', models.IntegerField(null=True, verbose_name='Donation Amount')),
                ('purpose', models.CharField(choices=[('Donation', 'Donation'), ('Education', 'Education'), ('Differently Abled', 'Differently Abled'), ('Medical Aid', 'Medical Aid'), ('Ration Support', 'Ration Support'), ('Women Empowerment', 'Women Empowerment'), ('Skill Developement', 'Skill Developement')], max_length=255, null=True, verbose_name='Purpose')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=255, null=True, verbose_name='Donation Status')),
                ('isMonthly', models.BooleanField(default=False, null=True, verbose_name='Monthly Donation')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
