# Generated by Django 3.1.7 on 2021-05-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changemaker', '0005_auto_20210513_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='changemaker',
            name='status',
            field=models.CharField(choices=[('Patrons', 'Patrons'), ('Executive Board Members', 'Executive Board Members'), ('Advisory Board Member', 'Advisory Board Member'), ('Member', 'Member'), ('Honorary Member', 'Hono rary Member'), ('Supporting Member', 'Supporting Member'), ('Associates', 'Associates'), ('Workforce', 'Workforce'), ('Volunteer', 'Volunteer'), ('Interns', 'Interns')], max_length=255, null=True, verbose_name='Change Maker Status'),
        ),
        migrations.AlterField(
            model_name='changemaker',
            name='uniqueID',
            field=models.CharField(default='388B4', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='uniqueID',
            field=models.CharField(default='60E3F', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='studentID'),
        ),
    ]
