# Generated by Django 3.1.7 on 2021-05-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changemaker', '0006_auto_20210513_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changemaker',
            name='status',
        ),
        migrations.AlterField(
            model_name='changemaker',
            name='uniqueID',
            field=models.CharField(default='160AF', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='uniqueID',
            field=models.CharField(default='ACF8D', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='studentID'),
        ),
    ]
