# Generated by Django 3.1.7 on 2021-05-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changemaker', '0017_auto_20210519_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changemaker',
            name='uniqueID',
            field=models.CharField(default='82912', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='uniqueID',
            field=models.CharField(default='D6C4C', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='studentID'),
        ),
    ]
