# Generated by Django 3.1.7 on 2021-05-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changemaker', '0021_auto_20210520_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changemaker',
            name='uniqueID',
            field=models.CharField(default='B3390', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='uniqueID',
            field=models.CharField(default='19B09', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='studentID'),
        ),
    ]
