# Generated by Django 3.1.7 on 2021-05-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changemaker', '0023_auto_20210520_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changemaker',
            name='category',
        ),
        migrations.RemoveField(
            model_name='changemaker',
            name='education',
        ),
        migrations.RemoveField(
            model_name='changemaker',
            name='martialStatus',
        ),
        migrations.RemoveField(
            model_name='changemaker',
            name='motherName',
        ),
        migrations.RemoveField(
            model_name='changemaker',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='changemaker',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='changemaker',
            name='signature',
        ),
        migrations.AlterField(
            model_name='changemaker',
            name='profilePicture',
            field=models.ImageField(null=True, upload_to='', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='changemaker',
            name='uniqueID',
            field=models.CharField(default='086CE', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='uniqueID',
            field=models.CharField(default='B991B', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='studentID'),
        ),
    ]
