# Generated by Django 3.1.7 on 2021-05-28 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('changemaker', '0033_auto_20210526_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changemaker',
            name='uniqueID',
            field=models.CharField(default='DFA63', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='uniqueID',
            field=models.CharField(default='F1175', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='studentID'),
        ),
        migrations.CreateModel(
            name='MonthlyDonation',
            fields=[
                ('uniqueID', models.CharField(default='2C0CE', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='studentID')),
                ('amount', models.IntegerField(null=True, verbose_name='Donation Amount')),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=255, null=True, verbose_name='Month')),
                ('purpose', models.CharField(choices=[('Donation', 'Donation'), ('Education', 'Education'), ('Differently Abled', 'Differently Abled'), ('Medical Aid', 'Medical Aid'), ('Ration Support', 'Ration Support'), ('Women Empowerment', 'Women Empowerment'), ('Skill Developement', 'Skill Developement')], max_length=255, null=True, verbose_name='Purpose')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=255, null=True, verbose_name='Donation Status')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
