# Generated by Django 3.1.7 on 2021-05-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changemaker', '0034_auto_20210528_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changemaker',
            name='uniqueID',
            field=models.CharField(default='C408E', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='uniqueID',
            field=models.CharField(default='72295', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='studentID'),
        ),
        migrations.AlterField(
            model_name='monthlydonation',
            name='uniqueID',
            field=models.CharField(default='C487D', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='studentID'),
        ),
    ]
