# Generated by Django 3.1.7 on 2021-05-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changemaker', '0035_auto_20210528_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='changemaker',
            name='autoDebiting',
            field=models.BooleanField(default=False, null=True, verbose_name='Auto-Debiting'),
        ),
        migrations.AddField(
            model_name='changemaker',
            name='goldenDate',
            field=models.DateField(null=True, verbose_name='Golden Date of Giving'),
        ),
        migrations.AddField(
            model_name='changemaker',
            name='monthlyAmount',
            field=models.IntegerField(null=True, verbose_name='Monthly Donation Amount'),
        ),
        migrations.AddField(
            model_name='changemaker',
            name='monthlyPurpose',
            field=models.CharField(choices=[('Donation', 'Donation'), ('Education', 'Education'), ('Differently Abled', 'Differently Abled'), ('Medical Aid', 'Medical Aid'), ('Ration Support', 'Ration Support'), ('Women Empowerment', 'Women Empowerment'), ('Skill Developement', 'Skill Developement')], max_length=25, null=True, verbose_name='Purpose of Donation'),
        ),
        migrations.AddField(
            model_name='donation',
            name='isMonthly',
            field=models.BooleanField(default=False, null=True, verbose_name='Monthly Donation'),
        ),
        migrations.AlterField(
            model_name='changemaker',
            name='uniqueID',
            field=models.CharField(default='10C64', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='uniqueID',
            field=models.CharField(default='A9A85', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='studentID'),
        ),
        migrations.DeleteModel(
            name='MonthlyDonation',
        ),
    ]
