# Generated by Django 3.1.7 on 2021-05-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changemaker', '0038_auto_20210530_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='changemaker',
            name='isMonthly',
            field=models.BooleanField(default=False, null=True, verbose_name='Is Monthly'),
        ),
        migrations.AlterField(
            model_name='changemaker',
            name='uniqueID',
            field=models.CharField(default='58D85', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='uniqueID',
            field=models.CharField(default='758E9', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='studentID'),
        ),
    ]
