# Generated by Django 3.1.7 on 2021-05-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changemaker', '0040_auto_20210530_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changemaker',
            name='goldenDate',
            field=models.IntegerField(null=True, verbose_name='Golden Date of Giving'),
        ),
        migrations.AlterField(
            model_name='changemaker',
            name='uniqueID',
            field=models.CharField(default='B3006', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='uniqueID',
            field=models.CharField(default='AD299', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='studentID'),
        ),
    ]
