# Generated by Django 3.2.4 on 2021-06-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changemaker', '0041_auto_20210530_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changemaker',
            name='uniqueID',
            field=models.CharField(default='54FBC', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='uniqueID',
            field=models.CharField(default='C40F1', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='studentID'),
        ),
    ]
