# Generated by Django 3.1.7 on 2021-06-08 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('changemaker', '0046_auto_20210605_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True, verbose_name='Interest')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True, verbose_name='Skill')),
            ],
        ),
        migrations.AlterField(
            model_name='changemaker',
            name='uniqueID',
            field=models.CharField(default='66FA9', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='uniqueID',
            field=models.CharField(default='18184', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='studentID'),
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(choices=[('Nil', 'Nil'), ('5th Grade', '5th Grade'), ('6th Grade', '6th Grade'), ('7th Grade', '7th Grade'), ('8th Grade', '8th Grade'), ('9th Grade', '9th Grade'), ('10th Grade', '10th Grade'), ('11th Grade', '11th Grade'), ('12th Grade', '12th Grade'), ('Graduate', 'Graduate'), ('Post Graduate', 'Post Graduate')], max_length=25, null=True, verbose_name='Education')),
                ('specialization', models.CharField(max_length=250, null=True, verbose_name='Specialization')),
                ('duration', models.CharField(choices=[('1 Year', '1 Year'), ('5 Year', '5 Year'), ('10 Year', '10 Year'), ('Lifetime', 'Lifetime')], max_length=25, null=True, verbose_name='Duration')),
                ('hours', models.IntegerField(null=True, verbose_name='Volunteering Hours')),
                ('changemaker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='changemaker.changemaker')),
                ('interests', models.ManyToManyField(to='changemaker.Interest')),
                ('skills', models.ManyToManyField(to='changemaker.Skill')),
            ],
        ),
    ]
