# Generated by Django 3.1.7 on 2021-06-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changemaker', '0047_auto_20210608_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='changemaker',
            name='isVolunteer',
            field=models.BooleanField(default=False, null=True, verbose_name='Is Volunteer'),
        ),
        migrations.AlterField(
            model_name='changemaker',
            name='uniqueID',
            field=models.CharField(default='F8203', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='uniqueID',
            field=models.CharField(default='43D2A', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='studentID'),
        ),
    ]
