# Generated by Django 3.1.7 on 2021-06-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changemaker', '0048_auto_20210608_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changemaker',
            name='uniqueID',
            field=models.CharField(default='0644A', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='uniqueID',
            field=models.CharField(default='59E33', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='studentID'),
        ),
    ]
