# Generated by Django 3.2.4 on 2021-06-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changemaker', '0050_auto_20210623_0054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changemaker',
            old_name='goldenDate',
            new_name='goldenDay',
        ),
        migrations.AlterField(
            model_name='changemaker',
            name='uniqueID',
            field=models.CharField(default='48E3A', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='uniqueID',
            field=models.CharField(default='4CB09', editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='studentID'),
        ),
    ]
